from __future__ import annotations

from typing import List

from . import FilterFunctionT
from . import JSONPathNode
from . import Segments

class JSONPath:
    def __init__(
        self, environment: JSONPathEnvironment, segments: Segments
    ) -> None: ...
    def query(self, data: object) -> List[JSONPathNode]: ...
    def findall(self, data: object) -> List[object]: ...

class JSONPathEnvironment:
    def __init__(self) -> None: ...
    def register_function(self, name: str, func: FilterFunctionT) -> None: ...
    def compile(self, path: str): ...  # noqa: A003
    def findall(self, path: str, data: object) -> List[object]: ...
    def query(self, path: str, data: object) -> List[JSONPathNode]: ...
